### PR TITLE
fix: Rename deprecated `vim.treesitter` calls

### PR DESCRIPTION
**Pull request by dtomvan**
ref: neovim/neovim@cbbf8bd

### CODE REVIEW

**Comment by clason** [comment]
Thank you, but that would break users on 0.8. You should be using nvim-treesitter's new compat module; see the recent PR there.

**Comment by dtomvan** [comment]
Alright. Did you mean this when you said "compat module": nvim-treesitter/nvim-treesitter@789961cadccde4ed081c12c17da2add43b10d447?

**Comment by clason** [comment]
Yes, exactly!

**Comment by dtomvan** [comment]
OK, I will try to contribute some of the compatibility shims I need, then I'll try to get back to you.

**Comment by clason** [comment]
Can't you just use the ones from nvim-treesitter? Or is there one missing that you'd need?

**Comment by dtomvan** [comment]
I would need [these two](https://github.com/nvim-treesitter/nvim-treesitter/pull/4555/files#diff-527f9cd83e20be91b2a7038bdd74d7de5a495df062eb7b329c222d52b24da250R23-R30).

**Comment by dtomvan** [comment]
Hi, can this be merged? I'm sorry if I'm wasting your time.

**Comment by wookayin** [comment]
This seems to make neovim 0.7-0.8 broken with the playground plugin installed.

**Comment by theHamsta** [comment]
Yes, the compat module was just used in some places. Could you create a PR that would use it everywhere in this diff?

**Pull request merged**
