### PR TITLE
feat: add `TSHighlightCapturesUnderCursor` to show hl matches under cursor

### PR DESCRIPTION
**Pull request by theHamsta**
image

### CODE REVIEW

**Comment by theHamsta** [comment]
Warning: this implementation is slow in big files.

**Review by steelsojka — APPROVED** [review]
Looks good to me!

**Comment by unphased** [comment]
The `:TSHighlightCapturesUnderCursor` now does not show the computed linked highlight group anymore. 
image

Can we get it back or is there another helper that can show this? I'm not well versed in how to look up how TS will translate a node to highlight groups right now.

**Comment by unphased** [comment]
Also, `:TSCaptureUnderCursor` appears to do the same thing as `:TSHighlightCapturesUnderCursor`, is this a bug?

**Comment by unphased** [comment]
Alright `:Inspect` is the ticket...

**Pull request merged**
