### PR TITLE
[WIP] Hl group for each node !

### PR DESCRIPTION
**Pull request by kyazdani42**
thanks extmarks :)
wip because we might want to disable that feature by default, it's a little bit heavy on the eyes.

### CODE REVIEW

**Comment by kyazdani42** [comment]
@steelsojka i'm not sure i placed stuff in the right place, i've scripted that in a very small amount of time so tell me if you have refactorings suggestion.
Also should we make a command to enable/disable it or a keymap ?

**Comment by steelsojka** [comment]
@kyazdani42 I think a keybinding would be fine for disable/enable. I have no preference either way. If we can toggle it on or off then I don't think we need an enable/disable option. Just have it disabled by default and just toggle on with the keybinding.

**Comment by kyazdani42** [comment]
I'm done, make your review and i'll add the docs altogether with the requested changes :)

**Review by steelsojka — APPROVED** [review]
Awesome!

**Pull request merged**
